### ISSUE TITLE
As a developer, I require a framework for SQL handling

### ISSUE THREAD

**Issue by Zimm** [BauPhi/bauphi-backend#7]
As a developer, I need methods and classes that makes related queries which backend requires for its API interactions.

**Comment by tunahanertekin** [comment]
.createTable('announcement', table => {
        table.increments('announcement_id').primary()
        table.integer('event_starter').references('userid').inTable('users')
        table.binary('image', [2048])
        table.string('phone')
        table.string('title')
        table.string('description')
        table.inherits('events')
    })

- Announcement shouldn't inherit Event, a bugfix is needed.
- Also, a seperator field to identify whether the announcement is for people or pets. A boolean field may be sufficient such as `isHuman`.

**Comment by Zimm** [comment]
It appears to be this kind of sql actions can be handled within knex and db functions class.
