### ISSUE TITLE
As a developer, I need a framework to handle login attemps from Facebook/Google accounts

### ISSUE THREAD

**Issue by Zimm** [BauPhi/bauphi-backend#8]
As a developer, I need a framework to handle Facebook/Google login attempts from mobile clients and the web browsers.

**Comment by tunahanertekin** [comment]
# Login Using OAuth
It is written to make users be able to login with their Gmail account. If it's their first login with a Google account, they will be registered and given a `session_key`. If not, their credentials will be checked and they will be given a `session_key` if their credentials hold.

## Request
- Type: POST
- URL: /api/users/google-auth

| Body Parameter  | Description | Obligation
| ------------- | ------------- | -------------
| access_token  | Access token returned by Google/Firebase. | Yes



## Response
- In success, user & session credentials are returned.
```json
{
    "status": "SUCCESS",
    "message": "user is logged in using a google account",
    "user": {
        "user_id": 22,
        "name": "discuss",
        "surname": "bank",
        "email": "connectionbauphi@gmail.com",
        "phone": "",
        "password": "6181738008c985a1b5f106b796c98e719efcc3c0ff68ddcd14a049825f4900a8",
        "registration_id": "notset",
        "is_oauth_user": true,
        "google_sub_id": "108797461518181707543"
    },
    "session": {
        "user_id": 22,
        "session_key": "6Oul3E",
        "start_time": "2021-04-15T17:18:57.110Z",
        "expire_time": "2021-04-16T05:18:57.110Z"
    }
}
```
- In failure, an error message is returned
```json
{
    "status": "FAILURE",
    "message": "request body fields are not true"
}
```

**Comment by tunahanertekin** [comment]
# Process

1. Frontend gets an Google access token with Firebase auth functions.
2. Frontend sends the access token to the backend.
3. Backend retrieves user data from Google using access token. (Google sub_id and email)
4. Backend confirms/saves the user and gives a session_key. (or deny)

Resources: 
[Google Sign-In with Firebase](https://firebase.google.com/docs/auth/web/google-signin)
[Verifying the User Info](https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/)
